"use client";

import React, { useEffect, useMemo, useRef, useState } from "react";

type SalaryRecord = {
  id: string;
  _id?: string;
  createdAt?: string;
  updatedAt?: string;
  [key: string]: string | number | undefined;
};

type BulkPreviewRow = {
  rowNumber: number;
  data: SalaryRecord;
  errors: Record<string, string>;
  warnings: string[];
  action: "insert" | "update" | "skip";
};

type ImportProgress = {
  total: number;
  done: number;
  failed: number;
};

const API_URL = "/api/payroll-service/salary-sheet";

const coreFields = [
  "Employee ID",
  "Employee Name",
  "Designation",
  "Department",
  "Basic Salary",
  "House Rent",
  "Medical Allowance",
  "Conveyance Allowance",
  "Gross Salary",
  "Total Earnings",
  "Total Deductions",
  "Net Salary",
  "Payroll Month",
  "Payroll Year",
  "Payroll Status",
];

const extraFields = [
  "Employee Code",
  "Branch",
  "Shift",
  "Grade",
  "Employment Type",
  "Reporting Manager",
  "Joining Date",
  "Working Days",
  "Present Days",
  "Absent Days",
  "Leave Days",
  "Tiffin Allowance",
  "Mobile Bill Allowance",
  "Project Bonus",
  "Festival Bonus",
  "Performance Bonus",
  "Attendance Bonus",
  "Incentive",
  "Other Allowances",
  "Overtime Hours",
  "Overtime Amount",
  "Provident Fund (PF)",
  "Income Tax",
  "Advance Salary Deduction",
  "Loan Deduction",
  "Absent Deduction",
  "Late Attendance Deduction",
  "Other Deductions",
  "Taxable Income",
  "Non-Taxable Income",
  "Arrear Salary",
  "Salary Adjustment",
  "Bonus Adjustment",
  "Deduction Adjustment",
  "Payment Method",
  "Bank Name",
  "Bank Account Number",
  "Mobile Banking Number",
  "Payment Date",
  "Salary Scale",
  "Cost Center",
  "Pay Slip Number",
  "Final Settlement",
  "Approved By",
  "Generated By",
  "Remarks",

  /*
    2026 enterprise payroll readiness fields.
    Existing fields/features are kept intact; these fields extend the sheet,
    form, table, CSV export, payslip and MongoDB payload.
  */
  "Currency",
  "Exchange Rate",
  "Payroll Batch ID",
  "Approval Level",
  "Compliance Status",
  "Risk Score",
  "AI Anomaly Flag",
  "Digital Payslip URL",
  "E-Signature Status",
  "GL Account",
  "Payment Reference",
  "Data Source",
];

const requiredFields = [
  "Employee ID",
  "Employee Name",
  "Designation",
  "Department",
  "Basic Salary",
  "Payroll Month",
  "Payroll Year",
  "Payroll Status",
];

const calculatedFields = [
  "House Rent",
  "Medical Allowance",
  "Conveyance Allowance",
  "Gross Salary",
  "Total Earnings",
  "Total Deductions",
  "Net Salary",
  "Provident Fund (PF)",
  "Income Tax",
  "Taxable Income",
  "Overtime Amount",
  "Absent Deduction",
  "Payroll Batch ID",
  "Compliance Status",
  "Risk Score",
  "AI Anomaly Flag",
];

const numberFields = [
  "Basic Salary",
  "House Rent",
  "Medical Allowance",
  "Conveyance Allowance",
  "Gross Salary",
  "Total Earnings",
  "Total Deductions",
  "Net Salary",
  "Payroll Year",
  "Working Days",
  "Present Days",
  "Absent Days",
  "Leave Days",
  "Tiffin Allowance",
  "Mobile Bill Allowance",
  "Project Bonus",
  "Festival Bonus",
  "Performance Bonus",
  "Attendance Bonus",
  "Incentive",
  "Other Allowances",
  "Overtime Hours",
  "Overtime Amount",
  "Provident Fund (PF)",
  "Income Tax",
  "Advance Salary Deduction",
  "Loan Deduction",
  "Absent Deduction",
  "Late Attendance Deduction",
  "Other Deductions",
  "Taxable Income",
  "Non-Taxable Income",
  "Arrear Salary",
  "Salary Adjustment",
  "Bonus Adjustment",
  "Deduction Adjustment",
  "Exchange Rate",
  "Risk Score",
];

const amountFields = numberFields.filter(
  (field) =>
    ![
      "Payroll Year",
      "Working Days",
      "Present Days",
      "Absent Days",
      "Leave Days",
      "Overtime Hours",
      "Exchange Rate",
      "Risk Score",
    ].includes(field)
);

const dateFields = ["Joining Date", "Payment Date"];

const payrollMonths = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

const payrollStatuses = [
  "Draft",
  "Pending",
  "Approved",
  "Paid",
  "On Hold",
  "Cancelled",
];

const paymentMethods = [
  "Cash",
  "Bank Transfer",
  "Cheque",
  "Mobile Banking",
  "BEFTN",
  "NPSB",
  "RTGS",
  "Other",
];

const CUSTOM_FIELDS_KEY = "awm_advanced_salary_custom_fields";
const BULK_IMPORT_CHUNK_SIZE = 12;

function getCurrentMonthName() {
  return payrollMonths[new Date().getMonth()];
}

function currency(value: unknown) {
  const amount = Number(value || 0);
  return new Intl.NumberFormat("en-BD", {
    style: "currency",
    currency: "BDT",
    maximumFractionDigits: 0,
  }).format(amount);
}

function toNumber(value: unknown) {
  if (typeof value === "number") return Number.isFinite(value) ? value : 0;

  const raw = String(value ?? "").trim();
  if (!raw) return 0;

  const negativeByParentheses = /^\(.*\)$/.test(raw);
  const cleaned = raw
    .replace(/[৳$,£€₹BDTbdt\s]/g, "")
    .replace(/[^\d.-]/g, "");

  const number = Number(cleaned);
  if (!Number.isFinite(number)) return 0;

  return negativeByParentheses ? -Math.abs(number) : number;
}

function round2(value: number) {
  return Math.round(value * 100) / 100;
}

function calculateIncomeTax(basicSalary: number) {
  if (basicSalary <= 30000) return 0;
  if (basicSalary <= 100000) return basicSalary * 0.05;
  return basicSalary * 0.1;
}

function normalizeKey(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]/g, "");
}

function escapeHtml(value: unknown) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function createEmptyForm(customFields: string[] = []): SalaryRecord {
  const now = new Date();
  const record: SalaryRecord = {
    id: "",
    "Payroll Month": getCurrentMonthName(),
    "Payroll Year": now.getFullYear(),
    "Payroll Status": "Draft",
    "Working Days": 30,
    "Present Days": 30,
    "Absent Days": 0,
    "Leave Days": 0,
    Currency: "BDT",
    "Exchange Rate": 1,
    "Approval Level": "Level 1",
    "Compliance Status": "Pending Check",
    "AI Anomaly Flag": "No",
    "E-Signature Status": "Not Signed",
    "Data Source": "Manual",
  };

  [...coreFields, ...extraFields, ...customFields].forEach((field) => {
    if (record[field] === undefined) record[field] = "";
  });

  return record;
}

function getPayrollKey(record: SalaryRecord) {
  return [
    String(record["Employee ID"] ?? "").trim().toLowerCase(),
    String(record["Payroll Month"] ?? "").trim().toLowerCase(),
    String(record["Payroll Year"] ?? "").trim(),
  ].join("::");
}

function applySalaryAutomation(input: SalaryRecord): SalaryRecord {
  const next = { ...input };

  const basicSalary = toNumber(next["Basic Salary"]);
  const workingDays = toNumber(next["Working Days"]);
  const presentDays = toNumber(next["Present Days"]);
  const absentDays = toNumber(next["Absent Days"]);
  const leaveDays = toNumber(next["Leave Days"]);
  const overtimeHours = toNumber(next["Overtime Hours"]);

  const dailyRate = workingDays > 0 ? basicSalary / workingDays : 0;
  const hourlyRate = dailyRate / 8;

  next["House Rent"] = round2(basicSalary * 0.4);
  next["Medical Allowance"] = round2(basicSalary * 0.1);
  next["Conveyance Allowance"] = round2(basicSalary * 0.05);
  next["Provident Fund (PF)"] = round2(basicSalary * 0.05);
  next["Income Tax"] = round2(calculateIncomeTax(basicSalary));
  next["Taxable Income"] = round2(basicSalary);
  next["Overtime Amount"] = round2(overtimeHours * hourlyRate * 1.5);
  next["Absent Deduction"] = round2(absentDays * dailyRate);

  const grossSalary =
    toNumber(next["Basic Salary"]) +
    toNumber(next["House Rent"]) +
    toNumber(next["Medical Allowance"]) +
    toNumber(next["Conveyance Allowance"]);

  const totalEarnings =
    grossSalary +
    toNumber(next["Tiffin Allowance"]) +
    toNumber(next["Mobile Bill Allowance"]) +
    toNumber(next["Project Bonus"]) +
    toNumber(next["Festival Bonus"]) +
    toNumber(next["Performance Bonus"]) +
    toNumber(next["Attendance Bonus"]) +
    toNumber(next["Incentive"]) +
    toNumber(next["Other Allowances"]) +
    toNumber(next["Overtime Amount"]) +
    toNumber(next["Non-Taxable Income"]) +
    toNumber(next["Arrear Salary"]) +
    toNumber(next["Salary Adjustment"]) +
    toNumber(next["Bonus Adjustment"]);

  const totalDeductions =
    toNumber(next["Provident Fund (PF)"]) +
    toNumber(next["Income Tax"]) +
    toNumber(next["Advance Salary Deduction"]) +
    toNumber(next["Loan Deduction"]) +
    toNumber(next["Absent Deduction"]) +
    toNumber(next["Late Attendance Deduction"]) +
    toNumber(next["Other Deductions"]) +
    toNumber(next["Deduction Adjustment"]);

  next["Gross Salary"] = round2(grossSalary);
  next["Total Earnings"] = round2(totalEarnings);
  next["Total Deductions"] = round2(totalDeductions);
  next["Net Salary"] = round2(totalEarnings - totalDeductions);

  const month = String(next["Payroll Month"] || getCurrentMonthName());
  const year = String(next["Payroll Year"] || new Date().getFullYear());
  const monthIndex = Math.max(1, payrollMonths.indexOf(month) + 1);
  next["Payroll Batch ID"] = `PAY-${year}-${String(monthIndex).padStart(
    2,
    "0"
  )}`;

  let riskScore = 0;
  if (toNumber(next["Net Salary"]) < 0) riskScore += 50;
  if (workingDays > 0 && presentDays + absentDays + leaveDays > workingDays)
    riskScore += 40;
  if (basicSalary > 0 && toNumber(next["Total Deductions"]) > basicSalary * 0.5)
    riskScore += 25;
  if (overtimeHours > 80) riskScore += 20;
  if (absentDays > 10) riskScore += 15;
  if (String(next["Payment Method"] || "") === "Cash") riskScore += 5;

  next["Risk Score"] = Math.min(100, riskScore);
  next["AI Anomaly Flag"] =
    riskScore >= 50
      ? "High Risk"
      : riskScore >= 25
      ? "Review Needed"
      : "No";

  next["Compliance Status"] =
    riskScore >= 50
      ? "Blocked for Review"
      : riskScore >= 25
      ? "Needs Review"
      : "Compliant";

  if (!next.Currency) next.Currency = "BDT";
  if (!next["Exchange Rate"]) next["Exchange Rate"] = 1;
  if (!next["Data Source"]) next["Data Source"] = "Manual";
  if (!next["Approval Level"]) next["Approval Level"] = "Level 1";
  if (!next["E-Signature Status"]) next["E-Signature Status"] = "Not Signed";

  return next;
}

function downloadCSV(records: SalaryRecord[], columns: string[]) {
  const header = columns.map((column) => `"${column}"`).join(",");

  const rows = records.map((record) =>
    columns
      .map((field) => {
        const value = String(record[field] ?? "").replaceAll('"', '""');
        return `"${value}"`;
      })
      .join(",")
  );

  const csv = [header, ...rows].join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = `salary-sheet-${Date.now()}.csv`;
  link.click();

  URL.revokeObjectURL(url);
}

function parseDelimitedLine(line: string, delimiter: string) {
  const cells: string[] = [];
  let current = "";
  let insideQuotes = false;

  for (let index = 0; index < line.length; index += 1) {
    const char = line[index];
    const next = line[index + 1];

    if (char === '"' && insideQuotes && next === '"') {
      current += '"';
      index += 1;
      continue;
    }

    if (char === '"') {
      insideQuotes = !insideQuotes;
      continue;
    }

    if (char === delimiter && !insideQuotes) {
      cells.push(current.trim());
      current = "";
      continue;
    }

    current += char;
  }

  cells.push(current.trim());
  return cells;
}

function detectDelimiter(line: string) {
  const candidates = ["\t", ",", ";", "|"];
  const counts = candidates.map((delimiter) => ({
    delimiter,
    count: parseDelimitedLine(line, delimiter).length,
  }));

  const best = counts.sort((a, b) => b.count - a.count)[0];
  return best.count > 1 ? best.delimiter : "MULTI_SPACE";
}

function parseTableText(text: string) {
  const lines = text
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);

  if (!lines.length) return { rows: [] as string[][], delimiter: "\t" };

  const delimiter = detectDelimiter(lines[0]);

  const rows = lines.map((line) => {
    if (delimiter === "MULTI_SPACE") {
      return line.split(/\s{2,}/).map((cell) => cell.trim());
    }

    return parseDelimitedLine(line, delimiter);
  });

  return { rows, delimiter };
}

function normalizeDateValue(value: string) {
  const raw = value.trim();
  if (!raw) return "";

  if (/^\d{4}-\d{2}-\d{2}$/.test(raw)) return raw;

  const match = raw.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{2,4})$/);
  if (match) {
    const day = match[1].padStart(2, "0");
    const month = match[2].padStart(2, "0");
    const year = match[3].length === 2 ? `20${match[3]}` : match[3];
    return `${year}-${month}-${day}`;
  }

  const parsed = new Date(raw);
  if (!Number.isNaN(parsed.getTime())) {
    return parsed.toISOString().slice(0, 10);
  }

  return raw;
}

function normalizeImportValue(field: string, value: string) {
  const trimmed = String(value ?? "").trim();

  if (numberFields.includes(field)) return toNumber(trimmed);

  if (dateFields.includes(field)) return normalizeDateValue(trimmed);

  if (field === "Payroll Month") {
    const monthByNumber = Number(trimmed);
    if (Number.isInteger(monthByNumber) && monthByNumber >= 1 && monthByNumber <= 12) {
      return payrollMonths[monthByNumber - 1];
    }

    const found = payrollMonths.find(
      (month) => month.toLowerCase() === trimmed.toLowerCase()
    );
    return found || trimmed;
  }

  if (field === "Payroll Status") {
    const found = payrollStatuses.find(
      (status) => status.toLowerCase() === trimmed.toLowerCase()
    );
    return found || trimmed;
  }

  if (field === "Payment Method") {
    const found = paymentMethods.find(
      (method) => method.toLowerCase() === trimmed.toLowerCase()
    );
    return found || trimmed;
  }

  return trimmed;
}

function resolveImportHeader(header: string, fields: string[]) {
  const aliases: Record<string, string> = {
    empid: "Employee ID",
    employeeid: "Employee ID",
    staffid: "Employee ID",
    workerid: "Employee ID",
    empcode: "Employee Code",
    employeecode: "Employee Code",
    name: "Employee Name",
    employeename: "Employee Name",
    salary: "Basic Salary",
    basicsalary: "Basic Salary",
    basic: "Basic Salary",
    departmentname: "Department",
    dept: "Department",
    designationname: "Designation",
    month: "Payroll Month",
    payrollmonth: "Payroll Month",
    year: "Payroll Year",
    payrollyear: "Payroll Year",
    status: "Payroll Status",
    gross: "Gross Salary",
    grosssalary: "Gross Salary",
    net: "Net Salary",
    netsalary: "Net Salary",
    present: "Present Days",
    absent: "Absent Days",
    leave: "Leave Days",
    workingdays: "Working Days",
    overtime: "Overtime Hours",
    overtimehours: "Overtime Hours",
    ot: "Overtime Hours",
    pf: "Provident Fund (PF)",
    providentfund: "Provident Fund (PF)",
    tax: "Income Tax",
    incometax: "Income Tax",
    bankaccount: "Bank Account Number",
    bankaccountnumber: "Bank Account Number",
    mobilebanking: "Mobile Banking Number",
    mobilebankingnumber: "Mobile Banking Number",
    paymentmethod: "Payment Method",
    paymentdate: "Payment Date",
    paymentreference: "Payment Reference",
  };

  const normalizedHeader = normalizeKey(header);
  if (aliases[normalizedHeader] && fields.includes(aliases[normalizedHeader])) {
    return aliases[normalizedHeader];
  }

  return fields.find((field) => normalizeKey(field) === normalizedHeader) || "";
}

export default function SalarySheetPage() {
  const [records, setRecords] = useState<SalaryRecord[]>([]);
  const [formData, setFormData] = useState<SalaryRecord>(createEmptyForm());
  const [editingId, setEditingId] = useState<string | null>(null);

  const [customFields, setCustomFields] = useState<string[]>([]);
  const [customFieldName, setCustomFieldName] = useState("");

  const [isFormOpen, setIsFormOpen] = useState(false);
  const [isAddMenuOpen, setIsAddMenuOpen] = useState(false);
  const [isBulkOpen, setIsBulkOpen] = useState(false);

  const [bulkText, setBulkText] = useState("");
  const [importMode, setImportMode] = useState<"insert" | "upsert">("insert");
  const [bulkSaving, setBulkSaving] = useState(false);
  const [importProgress, setImportProgress] = useState<ImportProgress>({
    total: 0,
    done: 0,
    failed: 0,
  });

  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const [searchTerm, setSearchTerm] = useState("");
  const [departmentFilter, setDepartmentFilter] = useState("All");
  const [statusFilter, setStatusFilter] = useState("All");
  const [monthFilter, setMonthFilter] = useState("All");
  const [yearFilter, setYearFilter] = useState("All");

  const [budgetThreshold, setBudgetThreshold] = useState(500000);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const [toast, setToast] = useState<{
    type: "success" | "error" | "warning";
    message: string;
  } | null>(null);

  const printRef = useRef<HTMLDivElement | null>(null);

  const allFields = useMemo(
    () => [...coreFields, ...extraFields, ...customFields],
    [customFields]
  );

  useEffect(() => {
    try {
      const savedCustomFields = localStorage.getItem(CUSTOM_FIELDS_KEY);
      const parsedCustomFields: string[] = savedCustomFields
        ? JSON.parse(savedCustomFields)
        : [];

      setCustomFields(parsedCustomFields);
      setFormData(createEmptyForm(parsedCustomFields));
    } catch {
      setCustomFields([]);
      setFormData(createEmptyForm([]));
    }

    loadRecords();
  }, []);

  async function loadRecords() {
    setLoading(true);

    try {
      const response = await fetch(API_URL, { cache: "no-store" });

      if (!response.ok) {
        throw new Error("Failed to load salary records");
      }

      const data = await response.json();
      setRecords(data.records || []);
    } catch (error) {
      console.error(error);
      showToast("error", "Salary records load করতে সমস্যা হয়েছে।");
    } finally {
      setLoading(false);
    }
  }

  const departments = useMemo(() => {
    const list = records
      .map((record) => String(record["Department"] || "").trim())
      .filter(Boolean);

    return ["All", ...Array.from(new Set(list))];
  }, [records]);

  const years = useMemo(() => {
    const list = records
      .map((record) => String(record["Payroll Year"] || "").trim())
      .filter(Boolean);

    return ["All", ...Array.from(new Set(list)).sort().reverse()];
  }, [records]);

  const filteredRecords = useMemo(() => {
    const term = searchTerm.toLowerCase().trim();

    return records.filter((record) => {
      const employeeId = String(record["Employee ID"] || "").toLowerCase();
      const employeeName = String(record["Employee Name"] || "").toLowerCase();
      const designation = String(record["Designation"] || "").toLowerCase();
      const department = String(record["Department"] || "");
      const status = String(record["Payroll Status"] || "");
      const month = String(record["Payroll Month"] || "");
      const year = String(record["Payroll Year"] || "");

      const matchesSearch =
        !term ||
        employeeId.includes(term) ||
        employeeName.includes(term) ||
        designation.includes(term) ||
        department.toLowerCase().includes(term);

      const matchesDepartment =
        departmentFilter === "All" || department === departmentFilter;

      const matchesStatus = statusFilter === "All" || status === statusFilter;
      const matchesMonth = monthFilter === "All" || month === monthFilter;
      const matchesYear = yearFilter === "All" || year === yearFilter;

      return (
        matchesSearch &&
        matchesDepartment &&
        matchesStatus &&
        matchesMonth &&
        matchesYear
      );
    });
  }, [
    records,
    searchTerm,
    departmentFilter,
    statusFilter,
    monthFilter,
    yearFilter,
  ]);

  const totalEmployees = useMemo(() => {
    const ids = filteredRecords
      .map((record) => String(record["Employee ID"] || "").trim())
      .filter(Boolean);

    return new Set(ids).size;
  }, [filteredRecords]);

  const totalEarnings = useMemo(
    () =>
      filteredRecords.reduce(
        (sum, record) => sum + toNumber(record["Total Earnings"]),
        0
      ),
    [filteredRecords]
  );

  const totalDeductions = useMemo(
    () =>
      filteredRecords.reduce(
        (sum, record) => sum + toNumber(record["Total Deductions"]),
        0
      ),
    [filteredRecords]
  );

  const totalNetSalary = useMemo(
    () =>
      filteredRecords.reduce(
        (sum, record) => sum + toNumber(record["Net Salary"]),
        0
      ),
    [filteredRecords]
  );

  const averageSalary = useMemo(() => {
    if (!filteredRecords.length) return 0;
    return totalNetSalary / filteredRecords.length;
  }, [filteredRecords, totalNetSalary]);

  const paidCount = useMemo(
    () =>
      filteredRecords.filter((record) => record["Payroll Status"] === "Paid")
        .length,
    [filteredRecords]
  );

  const pendingCount = useMemo(
    () =>
      filteredRecords.filter((record) => record["Payroll Status"] === "Pending")
        .length,
    [filteredRecords]
  );

  const anomalyCount = useMemo(
    () =>
      filteredRecords.filter(
        (record) =>
          String(record["AI Anomaly Flag"] || "No") !== "No" ||
          toNumber(record["Risk Score"]) >= 25
      ).length,
    [filteredRecords]
  );

  const complianceIssueCount = useMemo(
    () =>
      filteredRecords.filter(
        (record) =>
          String(record["Compliance Status"] || "").toLowerCase() !==
            "compliant" && String(record["Compliance Status"] || "").trim()
      ).length,
    [filteredRecords]
  );

  const isBudgetExceeded = totalNetSalary > budgetThreshold;

  const bulkPreview = useMemo(() => {
    if (!bulkText.trim()) {
      return {
        rows: [] as BulkPreviewRow[],
        recognizedHeaders: [] as string[],
        skippedHeaders: [] as string[],
        totalRows: 0,
        validRows: 0,
        errorRows: 0,
        warningRows: 0,
      };
    }

    const parsed = parseTableText(bulkText);
    const tableRows = parsed.rows;

    if (!tableRows.length) {
      return {
        rows: [] as BulkPreviewRow[],
        recognizedHeaders: [] as string[],
        skippedHeaders: [] as string[],
        totalRows: 0,
        validRows: 0,
        errorRows: 0,
        warningRows: 0,
      };
    }

    const firstRow = tableRows[0];
    const mappedFirstRow = firstRow.map((header) =>
      resolveImportHeader(header, allFields)
    );
    const hasHeader = mappedFirstRow.filter(Boolean).length >= 2;

    const headers = hasHeader
      ? mappedFirstRow
      : firstRow.map((_, index) => allFields[index] || "");

    const bodyRows = hasHeader ? tableRows.slice(1) : tableRows;

    const recognizedHeaders = headers.filter(Boolean);
    const skippedHeaders = hasHeader
      ? firstRow.filter((_, index) => !headers[index])
      : [];

    const existingKeys = new Map<string, SalaryRecord>();
    records.forEach((record) => {
      existingKeys.set(getPayrollKey(record), record);
    });

    const builtRows: BulkPreviewRow[] = bodyRows.map((row, index) => {
      let data = createEmptyForm(customFields);
      data["Data Source"] = "Bulk Paste Import";

      row.forEach((cell, cellIndex) => {
        const field = headers[cellIndex];
        if (!field) return;
        data[field] = normalizeImportValue(field, cell);
      });

      data = applySalaryAutomation(data);

      const existing = existingKeys.get(getPayrollKey(data));
      const errorsForRow = validateSalaryRecord(data, null, records, {
        ignoreExistingDuplicate: importMode === "upsert",
      });

      const warnings: string[] = [];

      if (existing && importMode === "upsert") {
        warnings.push("Existing payroll record found: this row will update it.");
      }

      if (toNumber(data["Risk Score"]) >= 25) {
        warnings.push(
          `Risk score ${data["Risk Score"]}: ${data["AI Anomaly Flag"]}`
        );
      }

      return {
        rowNumber: hasHeader ? index + 2 : index + 1,
        data,
        errors: errorsForRow,
        warnings,
        action: existing ? (importMode === "upsert" ? "update" : "skip") : "insert",
      };
    });

    const duplicateCounter = new Map<string, number>();
    builtRows.forEach((row) => {
      const key = getPayrollKey(row.data);
      duplicateCounter.set(key, (duplicateCounter.get(key) || 0) + 1);
    });

    const finalRows = builtRows.map((row) => {
      const key = getPayrollKey(row.data);
      if (duplicateCounter.get(key)! > 1) {
        return {
          ...row,
          errors: {
            ...row.errors,
            "Employee ID":
              "Duplicate row in pasted data for same Employee ID + Payroll Month + Payroll Year",
          },
        };
      }

      return row;
    });

    return {
      rows: finalRows,
      recognizedHeaders,
      skippedHeaders,
      totalRows: finalRows.length,
      validRows: finalRows.filter((row) => !Object.keys(row.errors).length).length,
      errorRows: finalRows.filter((row) => Object.keys(row.errors).length).length,
      warningRows: finalRows.filter((row) => row.warnings.length).length,
    };
  }, [bulkText, allFields, customFields, records, importMode]);

  function showToast(
    type: "success" | "error" | "warning",
    message: string
  ) {
    setToast({ type, message });
    setTimeout(() => setToast(null), 3500);
  }

  function validateSalaryRecord(
    data: SalaryRecord,
    currentId: string | null,
    sourceRecords: SalaryRecord[],
    options?: { ignoreExistingDuplicate?: boolean }
  ) {
    const nextErrors: Record<string, string> = {};

    requiredFields.forEach((field) => {
      if (!String(data[field] ?? "").trim()) {
        nextErrors[field] = `${field} is required`;
      }
    });

    if (toNumber(data["Basic Salary"]) <= 0) {
      nextErrors["Basic Salary"] = "Basic Salary must be greater than 0";
    }

    const year = toNumber(data["Payroll Year"]);

    if (year < 2000 || year > 2100) {
      nextErrors["Payroll Year"] = "Payroll Year must be between 2000 and 2100";
    }

    if (
      data["Payroll Month"] &&
      !payrollMonths.includes(String(data["Payroll Month"]))
    ) {
      nextErrors["Payroll Month"] = "Invalid Payroll Month";
    }

    if (
      data["Payroll Status"] &&
      !payrollStatuses.includes(String(data["Payroll Status"]))
    ) {
      nextErrors["Payroll Status"] = "Invalid Payroll Status";
    }

    const workingDays = toNumber(data["Working Days"]);
    const presentDays = toNumber(data["Present Days"]);
    const absentDays = toNumber(data["Absent Days"]);
    const leaveDays = toNumber(data["Leave Days"]);

    if (workingDays < 0 || presentDays < 0 || absentDays < 0 || leaveDays < 0) {
      nextErrors["Working Days"] = "Days cannot be negative";
    }

    if (
      workingDays > 0 &&
      presentDays + absentDays + leaveDays > workingDays
    ) {
      nextErrors["Present Days"] =
        "Present + Absent + Leave Days cannot exceed Working Days";
    }

    if (
      data["Payroll Status"] === "Paid" &&
      !String(data["Payment Method"] ?? "").trim()
    ) {
      nextErrors["Payment Method"] = "Payment Method is required for paid salary";
    }

    if (toNumber(data["Net Salary"]) < 0) {
      nextErrors["Net Salary"] = "Net Salary cannot be negative";
    }

    if (!options?.ignoreExistingDuplicate) {
      const duplicate = sourceRecords.some(
        (record) =>
          record.id !== currentId &&
          String(record["Employee ID"]).trim().toLowerCase() ===
            String(data["Employee ID"]).trim().toLowerCase() &&
          String(record["Payroll Month"]) === String(data["Payroll Month"]) &&
          Number(record["Payroll Year"]) === Number(data["Payroll Year"])
      );

      if (duplicate) {
        nextErrors["Employee ID"] =
          "This employee already has a salary sheet for this payroll month/year";
      }
    }

    return nextErrors;
  }

  function validateForm(data: SalaryRecord) {
    return validateSalaryRecord(data, editingId, records);
  }

  function openCreateForm() {
    setEditingId(null);
    setErrors({});
    setFormData(createEmptyForm(customFields));
    setIsFormOpen(true);
  }

  function openEditForm(record: SalaryRecord) {
    if (
      record["Payroll Status"] === "Paid" &&
      !window.confirm(
        "This salary record is already Paid. Do you want to continue editing?"
      )
    ) {
      return;
    }

    setEditingId(record.id);
    setErrors({});
    setFormData(applySalaryAutomation({ ...createEmptyForm(customFields), ...record }));
    setIsFormOpen(true);
  }

  function handleInputChange(field: string, value: string | number) {
    setFormData((previous) => {
      const updated = {
        ...previous,
        [field]: value,
      };

      return applySalaryAutomation(updated);
    });

    if (errors[field]) {
      setErrors((previous) => {
        const next = { ...previous };
        delete next[field];
        return next;
      });
    }
  }

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();

    const finalData = applySalaryAutomation(formData);
    const validationErrors = validateForm(finalData);

    if (Object.keys(validationErrors).length) {
      setErrors(validationErrors);
      showToast("error", "ফর্মে required বা invalid field আছে।");
      return;
    }

    setSaving(true);

    try {
      const url = editingId
        ? `${API_URL}?id=${encodeURIComponent(editingId)}`
        : API_URL;

      const response = await fetch(url, {
        method: editingId ? "PUT" : "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(finalData),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.message || "Save failed");
      }

      const savedRecord = data.record as SalaryRecord;

      setRecords((previous) => {
        if (editingId) {
          return previous.map((record) =>
            record.id === editingId ? savedRecord : record
          );
        }

        return [savedRecord, ...previous];
      });

      setFormData(createEmptyForm(customFields));
      setEditingId(null);
      setIsFormOpen(false);
      setErrors({});

      showToast(
        "success",
        editingId
          ? "Salary record successfully updated."
          : "Salary record successfully saved."
      );
    } catch (error: any) {
      console.error(error);
      showToast("error", error.message || "Salary data save করতে সমস্যা হয়েছে।");
    } finally {
      setSaving(false);
    }
  }

  async function handleDelete(id: string) {
    const record = records.find((item) => item.id === id);

    if (
      record?.["Payroll Status"] === "Paid" &&
      !window.confirm(
        "This salary record is Paid. Deleting paid payroll data can affect audit history. Continue?"
      )
    ) {
      return;
    }

    if (!window.confirm("Are you sure you want to delete this salary record?")) {
      return;
    }

    try {
      const response = await fetch(`${API_URL}?id=${encodeURIComponent(id)}`, {
        method: "DELETE",
      });

      if (!response.ok) {
        throw new Error("Delete failed");
      }

      setRecords((previous) => previous.filter((record) => record.id !== id));
      showToast("success", "Salary record deleted successfully.");
    } catch (error) {
      console.error(error);
      showToast("error", "Salary record delete করতে সমস্যা হয়েছে।");
    }
  }

  function handleAddCustomField() {
    const field = customFieldName.trim();

    if (!field) {
      showToast("error", "Custom field name লিখুন।");
      return;
    }

    if (allFields.includes(field)) {
      showToast("warning", "এই field আগে থেকেই আছে।");
      return;
    }

    const updatedCustomFields = [...customFields, field];

    setCustomFields(updatedCustomFields);
    localStorage.setItem(CUSTOM_FIELDS_KEY, JSON.stringify(updatedCustomFields));
    setFormData((previous) => ({ ...previous, [field]: "" }));
    setCustomFieldName("");

    showToast("success", `${field} field added successfully.`);
  }

  function handleClearFilters() {
    setSearchTerm("");
    setDepartmentFilter("All");
    setStatusFilter("All");
    setMonthFilter("All");
    setYearFilter("All");
  }

  function handleDownloadImportTemplate() {
    const sample = applySalaryAutomation({
      ...createEmptyForm(customFields),
      "Employee ID": "EMP-001",
      "Employee Name": "Sample Employee",
      Designation: "Executive",
      Department: "HR",
      "Basic Salary": 50000,
      "Payroll Month": getCurrentMonthName(),
      "Payroll Year": new Date().getFullYear(),
      "Payroll Status": "Draft",
      "Payment Method": "Bank Transfer",
    });

    downloadCSV([sample], allFields);
  }

  async function saveOneImportedRecord(record: SalaryRecord) {
    const existing = records.find(
      (item) => getPayrollKey(item) === getPayrollKey(record)
    );

    const isUpdate = importMode === "upsert" && existing?.id;
    const url = isUpdate
      ? `${API_URL}?id=${encodeURIComponent(existing!.id)}`
      : API_URL;

    const response = await fetch(url, {
      method: isUpdate ? "PUT" : "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(record),
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.message || "Import save failed");
    }

    return data.record as SalaryRecord;
  }

  async function handleSaveBulkImport() {
    const validRows = bulkPreview.rows.filter(
      (row) => !Object.keys(row.errors).length
    );

    if (!validRows.length) {
      showToast("error", "No valid row found to import.");
      return;
    }

    if (bulkPreview.errorRows > 0) {
      const confirmed = window.confirm(
        `${bulkPreview.errorRows} invalid row(s) will be skipped. Continue importing ${validRows.length} valid row(s)?`
      );

      if (!confirmed) return;
    }

    setBulkSaving(true);
    setImportProgress({ total: validRows.length, done: 0, failed: 0 });

    const savedRecords: SalaryRecord[] = [];
    let failed = 0;

    try {
      for (let index = 0; index < validRows.length; index += BULK_IMPORT_CHUNK_SIZE) {
        const chunk = validRows.slice(index, index + BULK_IMPORT_CHUNK_SIZE);

        const results = await Promise.allSettled(
          chunk.map((row) => saveOneImportedRecord(applySalaryAutomation(row.data)))
        );

        results.forEach((result) => {
          if (result.status === "fulfilled") {
            savedRecords.push(result.value);
          } else {
            failed += 1;
            console.error(result.reason);
          }
        });

        setImportProgress((previous) => ({
          total: validRows.length,
          done: Math.min(validRows.length, previous.done + chunk.length),
          failed,
        }));
      }

      if (savedRecords.length) {
        setRecords((previous) => {
          const next = [...previous];

          savedRecords.forEach((saved) => {
            const index = next.findIndex((item) => item.id === saved.id);
            if (index >= 0) {
              next[index] = saved;
            } else {
              const duplicateIndex = next.findIndex(
                (item) => getPayrollKey(item) === getPayrollKey(saved)
              );

              if (duplicateIndex >= 0) next[duplicateIndex] = saved;
              else next.unshift(saved);
            }
          });

          return next;
        });
      }

      if (failed) {
        showToast(
          "warning",
          `${savedRecords.length} row imported, ${failed} row failed. Please review API/server logs.`
        );
      } else {
        showToast("success", `${savedRecords.length} salary rows imported successfully.`);
        setBulkText("");
        setIsBulkOpen(false);
      }

      loadRecords();
    } catch (error: any) {
      console.error(error);
      showToast("error", error.message || "Bulk import failed.");
    } finally {
      setBulkSaving(false);
    }
  }

  function handlePrintPayslip(record: SalaryRecord) {
    const html = `
      <html>
        <head>
          <title>Pay Slip - ${escapeHtml(record["Employee Name"] || "")}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 28px; color: #111827; }
            .header { display: flex; justify-content: space-between; border-bottom: 2px solid #111827; padding-bottom: 14px; margin-bottom: 20px; }
            h1 { margin: 0 0 6px; }
            .muted { color: #6b7280; }
            .grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px; margin-bottom: 20px; }
            .box { border: 1px solid #e5e7eb; padding: 12px; border-radius: 10px; }
            table { width: 100%; border-collapse: collapse; margin-top: 12px; }
            td, th { border: 1px solid #e5e7eb; padding: 9px; text-align: left; font-size: 13px; }
            th { background: #f3f4f6; width: 35%; }
            .net { font-size: 18px; font-weight: bold; background: #ecfdf5; color: #065f46; }
            .footer { margin-top: 50px; display: flex; justify-content: space-between; }
            .sign { width: 180px; border-top: 1px solid #111827; padding-top: 8px; text-align: center; }
            @media print { button { display: none; } }
          </style>
        </head>
        <body>
          <div class="header">
            <div>
              <h1>Salary Pay Slip</h1>
              <div class="muted">AWM-ERP Payroll Service</div>
            </div>
            <div>
              <strong>${escapeHtml(record["Payroll Month"] || "")} ${escapeHtml(
      record["Payroll Year"] || ""
    )}</strong><br/>
              <span class="muted">Status: ${escapeHtml(
                record["Payroll Status"] || ""
              )}</span>
            </div>
          </div>

          <div class="grid">
            <div class="box">
              <strong>Employee</strong><br/>
              ${escapeHtml(record["Employee Name"] || "")}<br/>
              ${escapeHtml(record["Employee ID"] || "")}<br/>
              ${escapeHtml(record["Designation"] || "")}
            </div>
            <div class="box">
              <strong>Payment</strong><br/>
              ${escapeHtml(record["Payment Method"] || "")}<br/>
              ${escapeHtml(record["Bank Name"] || "")}<br/>
              ${escapeHtml(record["Payment Date"] || "")}
            </div>
          </div>

          <table>
            ${allFields
              .map((field) => {
                const value = amountFields.includes(field)
                  ? currency(record[field])
                  : escapeHtml(record[field] ?? "");

                return `
                  <tr class="${field === "Net Salary" ? "net" : ""}">
                    <th>${escapeHtml(field)}</th>
                    <td>${value}</td>
                  </tr>
                `;
              })
              .join("")}
          </table>

          <div class="footer">
            <div class="sign">Employee Signature</div>
            <div class="sign">Authorized Signature</div>
          </div>

          <script>
            window.onload = function() { window.print(); };
          </script>
        </body>
      </html>
    `;

    const printWindow = window.open("", "_blank");

    if (!printWindow) return;

    printWindow.document.write(html);
    printWindow.document.close();
  }

  function renderField(field: string) {
    const value = formData[field] ?? "";
    const error = errors[field];

    const isRequired = requiredFields.includes(field);
    const isCalculated = calculatedFields.includes(field);
    const isNumber = numberFields.includes(field);
    const isDate = dateFields.includes(field);

    if (field === "Remarks") {
      return (
        <label key={field} className="field textarea-field">
          <span>
            {field} {isRequired && <b>*</b>}
          </span>
          <textarea
            value={String(value)}
            onChange={(event) => handleInputChange(field, event.target.value)}
            placeholder={`Enter ${field}`}
          />
          {error && <small>{error}</small>}
        </label>
      );
    }

    if (field === "Payroll Month") {
      return (
        <label key={field} className="field">
          <span>
            {field} {isRequired && <b>*</b>}
          </span>
          <select
            value={String(value)}
            onChange={(event) => handleInputChange(field, event.target.value)}
          >
            {payrollMonths.map((month) => (
              <option key={month} value={month}>
                {month}
              </option>
            ))}
          </select>
          {error && <small>{error}</small>}
        </label>
      );
    }

    if (field === "Payroll Status") {
      return (
        <label key={field} className="field">
          <span>
            {field} {isRequired && <b>*</b>}
          </span>
          <select
            value={String(value)}
            onChange={(event) => handleInputChange(field, event.target.value)}
          >
            {payrollStatuses.map((status) => (
              <option key={status} value={status}>
                {status}
              </option>
            ))}
          </select>
          {error && <small>{error}</small>}
        </label>
      );
    }

    if (field === "Payment Method") {
      return (
        <label key={field} className="field">
          <span>{field}</span>
          <select
            value={String(value)}
            onChange={(event) => handleInputChange(field, event.target.value)}
          >
            <option value="">Select Payment Method</option>
            {paymentMethods.map((method) => (
              <option key={method} value={method}>
                {method}
              </option>
            ))}
          </select>
          {error && <small>{error}</small>}
        </label>
      );
    }

    return (
      <label key={field} className="field">
        <span>
          {field} {isRequired && <b>*</b>}
        </span>
        <input
          type={isDate ? "date" : isNumber ? "number" : "text"}
          value={String(value)}
          readOnly={isCalculated}
          onChange={(event) => handleInputChange(field, event.target.value)}
          placeholder={`Enter ${field}`}
        />
        {error && <small>{error}</small>}
      </label>
    );
  }

  return (
    <main className="salary-page" ref={printRef}>
      <header className="topbar">
        <div>
          <p className="eyebrow">Payroll Service</p>
          <h1>Advanced Salary Sheet</h1>
          <p className="subtitle">
            MongoDB connected enterprise payroll system with salary automation,
            validation, edit, delete, filters, CSV export, printable payslip,
            compliance scoring, anomaly detection and bulk Excel/PDF paste import.
          </p>
        </div>

        <div className="header-actions">
          <button
            className="icon-button"
            type="button"
            onClick={() => setIsAddMenuOpen((previous) => !previous)}
            aria-label="Add custom field"
          >
            +
          </button>

          <button
            className="secondary-header-button"
            type="button"
            onClick={() => setIsBulkOpen(true)}
          >
            Bulk Paste Import
          </button>

          <button className="primary-button" type="button" onClick={openCreateForm}>
            New Salary Entry
          </button>

          {isAddMenuOpen && (
            <div className="add-menu">
              <h3>Add Dynamic Field</h3>
              <input
                value={customFieldName}
                onChange={(event) => setCustomFieldName(event.target.value)}
                placeholder="Example: Commission"
              />
              <button type="button" onClick={handleAddCustomField}>
                Add Field
              </button>
              <p>New fields will be added to form, table and MongoDB record.</p>
            </div>
          )}
        </div>
      </header>

      <section className="dashboard-grid">
        <article className="summary-card">
          <span>Total Employees</span>
          <strong>{totalEmployees}</strong>
          <p>Filtered unique employee count</p>
        </article>

        <article className="summary-card expense">
          <span>Total Net Salary</span>
          <strong>{currency(totalNetSalary)}</strong>
          <p>Based on current filters</p>
        </article>

        <article className="summary-card average">
          <span>Average Salary</span>
          <strong>{currency(averageSalary)}</strong>
          <p>Average net salary</p>
        </article>

        <article className="summary-card deduction">
          <span>Total Deductions</span>
          <strong>{currency(totalDeductions)}</strong>
          <p>Total deductions amount</p>
        </article>

        <article className="summary-card earning">
          <span>Total Earnings</span>
          <strong>{currency(totalEarnings)}</strong>
          <p>Gross plus allowances and bonus</p>
        </article>

        <article className="summary-card paid">
          <span>Paid Salary</span>
          <strong>{paidCount}</strong>
          <p>Paid payroll records</p>
        </article>

        <article className="summary-card pending">
          <span>Pending Salary</span>
          <strong>{pendingCount}</strong>
          <p>Pending payroll records</p>
        </article>

        <article className="summary-card risk">
          <span>AI Anomaly / Risk</span>
          <strong>{anomalyCount}</strong>
          <p>Rows needing payroll review</p>
        </article>

        <article className="summary-card compliance">
          <span>Compliance Issues</span>
          <strong>{complianceIssueCount}</strong>
          <p>Blocked or review-needed records</p>
        </article>

        <article className="summary-card budget">
          <span>Budget Threshold</span>
          <input
            type="number"
            value={budgetThreshold}
            onChange={(event) =>
              setBudgetThreshold(Number(event.target.value || 0))
            }
          />
          <p>Alert when total net salary exceeds budget</p>
        </article>
      </section>

      {isBudgetExceeded && (
        <section className="alert warning">
          ⚠️ Threshold Alert: Salary expense{" "}
          <b>{currency(totalNetSalary)}</b> exceeds budget{" "}
          <b>{currency(budgetThreshold)}</b>.
        </section>
      )}

      <section className="toolbar">
        <input
          value={searchTerm}
          onChange={(event) => setSearchTerm(event.target.value)}
          placeholder="Search employee, ID, designation or department"
        />

        <select
          value={departmentFilter}
          onChange={(event) => setDepartmentFilter(event.target.value)}
        >
          {departments.map((department) => (
            <option key={department} value={department}>
              {department}
            </option>
          ))}
        </select>

        <select
          value={statusFilter}
          onChange={(event) => setStatusFilter(event.target.value)}
        >
          <option value="All">All Status</option>
          {payrollStatuses.map((status) => (
            <option key={status} value={status}>
              {status}
            </option>
          ))}
        </select>

        <select
          value={monthFilter}
          onChange={(event) => setMonthFilter(event.target.value)}
        >
          <option value="All">All Month</option>
          {payrollMonths.map((month) => (
            <option key={month} value={month}>
              {month}
            </option>
          ))}
        </select>

        <select
          value={yearFilter}
          onChange={(event) => setYearFilter(event.target.value)}
        >
          {years.map((year) => (
            <option key={year} value={year}>
              {year === "All" ? "All Year" : year}
            </option>
          ))}
        </select>

        <button type="button" onClick={handleClearFilters}>
          Clear
        </button>

        <button type="button" onClick={() => downloadCSV(filteredRecords, allFields)}>
          Export CSV
        </button>

        <button type="button" onClick={handleDownloadImportTemplate}>
          Template
        </button>

        <button type="button" onClick={loadRecords}>
          Refresh
        </button>
      </section>

      <section className="table-card">
        <div className="table-header">
          <div>
            <h2>Salary Sheet Records</h2>
            <p>{loading ? "Loading..." : `${filteredRecords.length} records found`}</p>
          </div>
        </div>

        <div className="table-wrapper">
          <table>
            <thead>
              <tr>
                <th className="sticky-col">Actions</th>
                {allFields.map((field) => (
                  <th key={field}>{field}</th>
                ))}
              </tr>
            </thead>

            <tbody>
              {filteredRecords.length ? (
                filteredRecords.map((record) => (
                  <tr key={record.id}>
                    <td className="actions-cell sticky-col">
                      <button type="button" onClick={() => openEditForm(record)}>
                        Edit
                      </button>

                      <button type="button" onClick={() => handlePrintPayslip(record)}>
                        Payslip
                      </button>

                      <button
                        type="button"
                        className="danger"
                        onClick={() => handleDelete(record.id)}
                      >
                        Delete
                      </button>
                    </td>

                    {allFields.map((field) => (
                      <td key={field}>
                        {field === "Payroll Status" ? (
                          <span
                            className={`status-badge ${String(
                              record[field] || ""
                            )
                              .toLowerCase()
                              .replaceAll(" ", "-")}`}
                          >
                            {String(record[field] ?? "")}
                          </span>
                        ) : field === "AI Anomaly Flag" ? (
                          <span
                            className={`risk-badge ${String(record[field] || "no")
                              .toLowerCase()
                              .replaceAll(" ", "-")}`}
                          >
                            {String(record[field] ?? "")}
                          </span>
                        ) : amountFields.includes(field) ? (
                          currency(record[field])
                        ) : (
                          String(record[field] ?? "")
                        )}
                      </td>
                    ))}
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={allFields.length + 1} className="empty">
                    {loading
                      ? "Loading salary data..."
                      : "No salary data found. Click “New Salary Entry” to add data."}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </section>

      {isBulkOpen && (
        <section className="modal-backdrop">
          <div className="modal bulk-modal">
            <div className="modal-header">
              <div>
                <h2>Bulk Paste Import</h2>
                <p>
                  Copy thousands of rows from Excel, CSV, Google Sheets or
                  PDF-converted table and paste here. Headers are mapped
                  automatically and salary is recalculated before saving.
                </p>
              </div>

              <button
                type="button"
                className="close-button"
                onClick={() => {
                  if (!bulkSaving) setIsBulkOpen(false);
                }}
              >
                ×
              </button>
            </div>

            <div className="bulk-body">
              <div className="bulk-actions">
                <button type="button" onClick={handleDownloadImportTemplate}>
                  Download Template
                </button>

                <select
                  value={importMode}
                  onChange={(event) =>
                    setImportMode(event.target.value as "insert" | "upsert")
                  }
                >
                  <option value="insert">Insert only - duplicate rows blocked</option>
                  <option value="upsert">Upsert - update existing month/year</option>
                </select>

                <button type="button" onClick={() => setBulkText("")}>
                  Clear Paste
                </button>
              </div>

              <textarea
                className="bulk-textarea"
                value={bulkText}
                onChange={(event) => setBulkText(event.target.value)}
                placeholder={`Paste Excel/CSV data here. Recommended header examples:
Employee ID	Employee Name	Designation	Department	Basic Salary	Payroll Month	Payroll Year	Payroll Status
EMP-001	John Doe	Executive	HR	50000	January	2026	Draft`}
              />

              <div className="bulk-stats">
                <article>
                  <span>Total Rows</span>
                  <strong>{bulkPreview.totalRows}</strong>
                </article>
                <article className="valid">
                  <span>Valid</span>
                  <strong>{bulkPreview.validRows}</strong>
                </article>
                <article className="invalid">
                  <span>Invalid</span>
                  <strong>{bulkPreview.errorRows}</strong>
                </article>
                <article className="warning-stat">
                  <span>Warnings</span>
                  <strong>{bulkPreview.warningRows}</strong>
                </article>
              </div>

              {!!bulkPreview.recognizedHeaders.length && (
                <div className="mapping-info">
                  <b>Mapped columns:</b>{" "}
                  {bulkPreview.recognizedHeaders.join(", ")}
                  {!!bulkPreview.skippedHeaders.length && (
                    <>
                      <br />
                      <b>Skipped columns:</b> {bulkPreview.skippedHeaders.join(", ")}
                    </>
                  )}
                </div>
              )}

              {bulkSaving && (
                <div className="import-progress">
                  Importing {importProgress.done}/{importProgress.total} rows
                  {importProgress.failed ? `, failed ${importProgress.failed}` : ""}
                  <div>
                    <span
                      style={{
                        width: `${
                          importProgress.total
                            ? (importProgress.done / importProgress.total) * 100
                            : 0
                        }%`,
                      }}
                    />
                  </div>
                </div>
              )}

              <div className="bulk-preview-table">
                <table>
                  <thead>
                    <tr>
                      <th>Row</th>
                      <th>Action</th>
                      <th>Employee ID</th>
                      <th>Name</th>
                      <th>Department</th>
                      <th>Basic</th>
                      <th>Month</th>
                      <th>Year</th>
                      <th>Net Salary</th>
                      <th>Risk</th>
                      <th>Validation</th>
                    </tr>
                  </thead>

                  <tbody>
                    {bulkPreview.rows.slice(0, 50).map((row) => (
                      <tr
                        key={row.rowNumber}
                        className={
                          Object.keys(row.errors).length
                            ? "row-error"
                            : row.warnings.length
                            ? "row-warning"
                            : ""
                        }
                      >
                        <td>{row.rowNumber}</td>
                        <td>{row.action}</td>
                        <td>{String(row.data["Employee ID"] ?? "")}</td>
                        <td>{String(row.data["Employee Name"] ?? "")}</td>
                        <td>{String(row.data["Department"] ?? "")}</td>
                        <td>{currency(row.data["Basic Salary"])}</td>
                        <td>{String(row.data["Payroll Month"] ?? "")}</td>
                        <td>{String(row.data["Payroll Year"] ?? "")}</td>
                        <td>{currency(row.data["Net Salary"])}</td>
                        <td>{String(row.data["AI Anomaly Flag"] ?? "")}</td>
                        <td>
                          {Object.keys(row.errors).length ? (
                            <span className="error-text">
                              {Object.values(row.errors).join(" | ")}
                            </span>
                          ) : row.warnings.length ? (
                            <span className="warning-text">
                              {row.warnings.join(" | ")}
                            </span>
                          ) : (
                            <span className="success-text">Ready</span>
                          )}
                        </td>
                      </tr>
                    ))}

                    {!bulkPreview.rows.length && (
                      <tr>
                        <td colSpan={11} className="empty">
                          Paste data to see import preview.
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>

              {bulkPreview.rows.length > 50 && (
                <p className="preview-note">
                  Showing first 50 rows only. All {bulkPreview.totalRows} rows
                  will be validated and valid rows will be saved.
                </p>
              )}
            </div>

            <div className="form-actions">
              <button
                type="button"
                className="secondary-button"
                disabled={bulkSaving}
                onClick={() => setIsBulkOpen(false)}
              >
                Cancel
              </button>

              <button
                type="button"
                className="primary-button"
                disabled={bulkSaving || !bulkPreview.validRows}
                onClick={handleSaveBulkImport}
              >
                {bulkSaving
                  ? "Saving Bulk Data..."
                  : `Save ${bulkPreview.validRows} Valid Row(s)`}
              </button>
            </div>
          </div>
        </section>
      )}

      {isFormOpen && (
        <section className="modal-backdrop">
          <div className="modal">
            <div className="modal-header">
              <div>
                <h2>{editingId ? "Edit Salary Entry" : "New Salary Entry"}</h2>
                <p>
                  Basic salary, attendance and overtime will calculate salary
                  automatically.
                </p>
              </div>

              <button
                type="button"
                className="close-button"
                onClick={() => {
                  setIsFormOpen(false);
                  setEditingId(null);
                }}
              >
                ×
              </button>
            </div>

            <form onSubmit={handleSubmit}>
              <h3>Core Information</h3>
              <div className="form-grid">
                {coreFields.map((field) => renderField(field))}
              </div>

              <h3>Attendance, Allowances, Deductions, Payment & Compliance</h3>
              <div className="form-grid">
                {extraFields.map((field) => renderField(field))}
              </div>

              {customFields.length > 0 && (
                <>
                  <h3>Custom Dynamic Fields</h3>
                  <div className="form-grid">
                    {customFields.map((field) => renderField(field))}
                  </div>
                </>
              )}

              <div className="salary-preview">
                <div>
                  <span>Gross Salary</span>
                  <strong>{currency(formData["Gross Salary"])}</strong>
                </div>
                <div>
                  <span>Total Earnings</span>
                  <strong>{currency(formData["Total Earnings"])}</strong>
                </div>
                <div>
                  <span>Total Deductions</span>
                  <strong>{currency(formData["Total Deductions"])}</strong>
                </div>
                <div className="net-preview">
                  <span>Net Salary</span>
                  <strong>{currency(formData["Net Salary"])}</strong>
                </div>
                <div>
                  <span>Risk Score</span>
                  <strong>{String(formData["Risk Score"] ?? 0)}</strong>
                </div>
                <div>
                  <span>Compliance</span>
                  <strong>{String(formData["Compliance Status"] ?? "")}</strong>
                </div>
              </div>

              <div className="form-actions">
                <button
                  type="button"
                  className="secondary-button"
                  onClick={() => {
                    setIsFormOpen(false);
                    setEditingId(null);
                  }}
                >
                  Cancel
                </button>

                <button type="submit" className="primary-button" disabled={saving}>
                  {saving
                    ? "Saving..."
                    : editingId
                    ? "Update Salary Data"
                    : "Save Salary Data"}
                </button>
              </div>
            </form>
          </div>
        </section>
      )}

      {toast && <div className={`toast ${toast.type}`}>{toast.message}</div>}

      <style jsx global>{`
        * {
          box-sizing: border-box;
        }

        body {
          margin: 0;
          background: #f3f6fb;
          color: #0f172a;
          font-family: Inter, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, "Segoe UI", sans-serif;
        }

        button,
        input,
        select,
        textarea {
          font: inherit;
        }
      `}</style>

      <style jsx>{`
        .salary-page {
          min-height: 100vh;
          padding: 24px;
        }

        .topbar {
          position: relative;
          display: flex;
          justify-content: space-between;
          gap: 20px;
          align-items: flex-start;
          padding: 24px;
          border-radius: 24px;
          color: #fff;
          background: linear-gradient(135deg, #111827, #2563eb);
          box-shadow: 0 24px 60px rgba(15, 23, 42, 0.18);
        }

        .eyebrow {
          margin: 0 0 8px;
          color: #bfdbfe;
          font-weight: 800;
          text-transform: uppercase;
          letter-spacing: 0.12em;
          font-size: 12px;
        }

        h1,
        h2,
        h3,
        p {
          margin-top: 0;
        }

        h1 {
          margin-bottom: 8px;
          font-size: clamp(26px, 4vw, 42px);
        }

        .subtitle {
          max-width: 800px;
          margin-bottom: 0;
          color: #dbeafe;
          line-height: 1.6;
        }

        .header-actions {
          position: relative;
          display: flex;
          gap: 12px;
          align-items: center;
          flex-wrap: wrap;
          justify-content: flex-end;
        }

        .primary-button,
        .secondary-button,
        .secondary-header-button,
        .icon-button,
        .toolbar button,
        .add-menu button,
        .actions-cell button,
        .bulk-actions button {
          border: 0;
          cursor: pointer;
          border-radius: 12px;
          font-weight: 800;
          transition: 0.2s ease;
        }

        .primary-button {
          padding: 12px 18px;
          color: #fff;
          background: #10b981;
        }

        .primary-button:disabled,
        .secondary-button:disabled {
          opacity: 0.65;
          cursor: not-allowed;
        }

        .secondary-button {
          padding: 12px 18px;
          color: #111827;
          background: #e5e7eb;
        }

        .secondary-header-button {
          padding: 12px 18px;
          color: #0f172a;
          background: #e0f2fe;
        }

        .icon-button {
          width: 46px;
          height: 46px;
          color: #111827;
          background: #fff;
          font-size: 28px;
          line-height: 1;
        }

        .primary-button:hover,
        .icon-button:hover,
        .toolbar button:hover,
        .actions-cell button:hover,
        .secondary-header-button:hover,
        .bulk-actions button:hover {
          transform: translateY(-1px);
          filter: brightness(1.03);
        }

        .add-menu {
          position: absolute;
          right: 0;
          top: 58px;
          z-index: 20;
          width: 320px;
          padding: 18px;
          border-radius: 18px;
          color: #111827;
          background: #fff;
          box-shadow: 0 24px 60px rgba(15, 23, 42, 0.24);
        }

        .add-menu input,
        .add-menu button {
          width: 100%;
          margin-top: 10px;
        }

        .add-menu input {
          padding: 12px;
          border: 1px solid #d1d5db;
          border-radius: 12px;
        }

        .add-menu button {
          padding: 12px;
          color: #fff;
          background: #2563eb;
        }

        .add-menu p {
          margin: 12px 0 0;
          color: #6b7280;
          font-size: 13px;
        }

        .dashboard-grid {
          display: grid;
          grid-template-columns: repeat(5, minmax(0, 1fr));
          gap: 16px;
          margin-top: 20px;
        }

        .summary-card {
          padding: 20px;
          border-radius: 22px;
          background: #fff;
          box-shadow: 0 16px 40px rgba(15, 23, 42, 0.08);
          border-top: 5px solid #94a3b8;
        }

        .summary-card span {
          display: block;
          color: #64748b;
          font-weight: 800;
          margin-bottom: 8px;
        }

        .summary-card strong {
          display: block;
          font-size: 26px;
          margin-bottom: 6px;
        }

        .summary-card p {
          margin: 0;
          color: #64748b;
          font-size: 13px;
        }

        .summary-card.expense {
          border-top-color: #2563eb;
        }

        .summary-card.average {
          border-top-color: #10b981;
        }

        .summary-card.deduction {
          border-top-color: #ef4444;
        }

        .summary-card.earning {
          border-top-color: #8b5cf6;
        }

        .summary-card.paid {
          border-top-color: #22c55e;
        }

        .summary-card.pending {
          border-top-color: #f59e0b;
        }

        .summary-card.risk {
          border-top-color: #f97316;
        }

        .summary-card.compliance {
          border-top-color: #ec4899;
        }

        .summary-card.budget {
          border-top-color: #0f172a;
        }

        .summary-card.budget input {
          width: 100%;
          padding: 10px;
          border: 1px solid #d1d5db;
          border-radius: 12px;
          font-weight: 800;
          font-size: 20px;
        }

        .alert {
          margin-top: 18px;
          padding: 16px 18px;
          border-radius: 16px;
          font-weight: 800;
        }

        .alert.warning {
          color: #92400e;
          background: #fef3c7;
          border: 1px solid #f59e0b;
        }

        .toolbar {
          display: grid;
          grid-template-columns: 2fr repeat(4, 1fr) auto auto auto auto;
          gap: 12px;
          margin: 20px 0;
          padding: 16px;
          border-radius: 20px;
          background: #fff;
          box-shadow: 0 16px 40px rgba(15, 23, 42, 0.07);
        }

        .toolbar input,
        .toolbar select,
        .bulk-actions select {
          width: 100%;
          min-width: 140px;
          padding: 12px;
          border: 1px solid #d1d5db;
          border-radius: 12px;
        }

        .toolbar button,
        .bulk-actions button {
          padding: 12px 16px;
          color: #fff;
          background: #111827;
          white-space: nowrap;
        }

        .table-card {
          overflow: hidden;
          border-radius: 22px;
          background: #fff;
          box-shadow: 0 16px 40px rgba(15, 23, 42, 0.08);
        }

        .table-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 18px 20px;
          border-bottom: 1px solid #e5e7eb;
        }

        .table-header h2 {
          margin: 0 0 4px;
        }

        .table-header p {
          margin: 0;
          color: #64748b;
          font-weight: 700;
        }

        .table-wrapper,
        .bulk-preview-table {
          width: 100%;
          overflow-x: auto;
        }

        table {
          width: 100%;
          min-width: 2800px;
          border-collapse: collapse;
        }

        th,
        td {
          padding: 12px;
          border-bottom: 1px solid #e5e7eb;
          text-align: left;
          white-space: nowrap;
          font-size: 13px;
        }

        th {
          position: sticky;
          top: 0;
          z-index: 3;
          color: #334155;
          background: #f8fafc;
        }

        .sticky-col {
          position: sticky;
          left: 0;
          z-index: 4;
          background: #fff;
          box-shadow: 8px 0 18px rgba(15, 23, 42, 0.05);
        }

        th.sticky-col {
          background: #f8fafc;
        }

        .actions-cell {
          display: flex;
          gap: 8px;
        }

        .actions-cell button {
          padding: 8px 10px;
          color: #fff;
          background: #2563eb;
          font-size: 12px;
        }

        .actions-cell button.danger {
          background: #ef4444;
        }

        .status-badge,
        .risk-badge {
          display: inline-flex;
          padding: 5px 10px;
          border-radius: 999px;
          font-weight: 900;
          font-size: 12px;
          background: #e5e7eb;
          color: #111827;
        }

        .status-badge.paid {
          background: #dcfce7;
          color: #166534;
        }

        .status-badge.approved {
          background: #dbeafe;
          color: #1d4ed8;
        }

        .status-badge.pending {
          background: #fef3c7;
          color: #92400e;
        }

        .status-badge.draft {
          background: #f1f5f9;
          color: #475569;
        }

        .status-badge.cancelled,
        .status-badge.on-hold,
        .risk-badge.high-risk {
          background: #fee2e2;
          color: #991b1b;
        }

        .risk-badge.review-needed {
          background: #ffedd5;
          color: #9a3412;
        }

        .risk-badge.no {
          background: #dcfce7;
          color: #166534;
        }

        .empty {
          padding: 32px;
          text-align: center;
          color: #64748b;
        }

        .modal-backdrop {
          position: fixed;
          inset: 0;
          z-index: 50;
          display: flex;
          align-items: flex-start;
          justify-content: center;
          padding: 30px;
          background: rgba(15, 23, 42, 0.62);
          overflow-y: auto;
        }

        .modal {
          width: min(1180px, 100%);
          border-radius: 24px;
          background: #fff;
          box-shadow: 0 30px 80px rgba(0, 0, 0, 0.3);
        }

        .bulk-modal {
          width: min(1380px, 100%);
        }

        .modal-header {
          position: sticky;
          top: 0;
          z-index: 10;
          display: flex;
          justify-content: space-between;
          gap: 20px;
          padding: 22px;
          border-bottom: 1px solid #e5e7eb;
          border-radius: 24px 24px 0 0;
          background: #fff;
        }

        .modal-header h2 {
          margin-bottom: 4px;
        }

        .modal-header p {
          margin-bottom: 0;
          color: #64748b;
        }

        .close-button {
          width: 42px;
          height: 42px;
          border: 0;
          border-radius: 50%;
          cursor: pointer;
          font-size: 26px;
          background: #f1f5f9;
        }

        form,
        .bulk-body {
          padding: 22px;
        }

        form h3 {
          margin: 22px 0 12px;
          padding-left: 10px;
          border-left: 4px solid #2563eb;
        }

        .form-grid {
          display: grid;
          grid-template-columns: repeat(3, minmax(0, 1fr));
          gap: 14px;
        }

        .field {
          display: flex;
          flex-direction: column;
          gap: 7px;
        }

        .field span {
          color: #334155;
          font-weight: 800;
          font-size: 13px;
        }

        .field b {
          color: #ef4444;
        }

        .field input,
        .field select,
        .field textarea {
          width: 100%;
          padding: 12px;
          border: 1px solid #d1d5db;
          border-radius: 12px;
          background: #fff;
        }

        .field input[readonly] {
          color: #065f46;
          background: #ecfdf5;
          font-weight: 900;
        }

        .field textarea {
          min-height: 90px;
          resize: vertical;
        }

        .textarea-field {
          grid-column: span 3;
        }

        .field small {
          color: #dc2626;
          font-weight: 800;
        }

        .salary-preview,
        .bulk-stats {
          display: grid;
          grid-template-columns: repeat(4, minmax(0, 1fr));
          gap: 12px;
          margin-top: 24px;
          padding: 16px;
          border-radius: 18px;
          background: #f8fafc;
          border: 1px solid #e5e7eb;
        }

        .salary-preview div,
        .bulk-stats article {
          padding: 14px;
          border-radius: 14px;
          background: #fff;
        }

        .salary-preview span,
        .bulk-stats span {
          display: block;
          color: #64748b;
          font-weight: 800;
          margin-bottom: 6px;
          font-size: 13px;
        }

        .salary-preview strong,
        .bulk-stats strong {
          font-size: 20px;
        }

        .salary-preview .net-preview,
        .bulk-stats .valid {
          background: #ecfdf5;
          color: #065f46;
        }

        .bulk-stats .invalid {
          background: #fef2f2;
          color: #991b1b;
        }

        .bulk-stats .warning-stat {
          background: #fffbeb;
          color: #92400e;
        }

        .bulk-actions {
          display: grid;
          grid-template-columns: auto 1fr auto;
          gap: 12px;
          margin-bottom: 14px;
        }

        .bulk-textarea {
          width: 100%;
          min-height: 220px;
          padding: 14px;
          border: 1px solid #cbd5e1;
          border-radius: 16px;
          resize: vertical;
          font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas,
            "Liberation Mono", "Courier New", monospace;
          font-size: 13px;
          line-height: 1.5;
          background: #f8fafc;
        }

        .mapping-info,
        .preview-note,
        .import-progress {
          margin-top: 14px;
          padding: 12px 14px;
          border-radius: 14px;
          background: #eff6ff;
          color: #1e3a8a;
          font-size: 13px;
          line-height: 1.6;
        }

        .bulk-preview-table {
          margin-top: 14px;
          border: 1px solid #e5e7eb;
          border-radius: 16px;
        }

        .bulk-preview-table table {
          min-width: 1200px;
        }

        .row-error {
          background: #fff1f2;
        }

        .row-warning {
          background: #fffbeb;
        }

        .error-text {
          color: #dc2626;
          font-weight: 800;
        }

        .warning-text {
          color: #b45309;
          font-weight: 800;
        }

        .success-text {
          color: #047857;
          font-weight: 800;
        }

        .import-progress div {
          height: 10px;
          margin-top: 8px;
          overflow: hidden;
          border-radius: 999px;
          background: #dbeafe;
        }

        .import-progress span {
          display: block;
          height: 100%;
          border-radius: 999px;
          background: #2563eb;
          transition: width 0.2s ease;
        }

        .form-actions {
          position: sticky;
          bottom: 0;
          display: flex;
          justify-content: flex-end;
          gap: 12px;
          margin: 24px -22px -22px;
          padding: 18px 22px;
          border-top: 1px solid #e5e7eb;
          border-radius: 0 0 24px 24px;
          background: #fff;
        }

        .bulk-modal > .form-actions {
          margin: 0;
        }

        .toast {
          position: fixed;
          right: 22px;
          bottom: 22px;
          z-index: 100;
          max-width: 420px;
          padding: 14px 18px;
          border-radius: 16px;
          color: #fff;
          font-weight: 900;
          box-shadow: 0 18px 50px rgba(15, 23, 42, 0.22);
        }

        .toast.success {
          background: #10b981;
        }

        .toast.error {
          background: #ef4444;
        }

        .toast.warning {
          background: #f59e0b;
        }

        @media (max-width: 1200px) {
          .toolbar {
            grid-template-columns: repeat(2, minmax(0, 1fr));
          }

          .dashboard-grid {
            grid-template-columns: repeat(2, minmax(0, 1fr));
          }

          .form-grid,
          .salary-preview,
          .bulk-stats {
            grid-template-columns: repeat(2, minmax(0, 1fr));
          }

          .textarea-field {
            grid-column: span 2;
          }

          .bulk-actions {
            grid-template-columns: 1fr;
          }
        }

        @media (max-width: 720px) {
          .salary-page {
            padding: 14px;
          }

          .topbar {
            flex-direction: column;
            padding: 18px;
          }

          .header-actions {
            width: 100%;
            justify-content: space-between;
          }

          .add-menu {
            left: 0;
            right: auto;
            width: min(320px, 90vw);
          }

          .dashboard-grid,
          .toolbar,
          .form-grid,
          .salary-preview,
          .bulk-stats {
            grid-template-columns: 1fr;
          }

          .textarea-field {
            grid-column: span 1;
          }

          .modal-backdrop {
            padding: 12px;
          }

          .form-actions {
            flex-direction: column;
          }

          .form-actions button {
            width: 100%;
          }
        }
      `}</style>
    </main>
  );
}