export const SECURITY_CONSTANTS = {
  TOKEN_ISSUER: "awm-erp",
  TOKEN_AUDIENCE: "awm-erp-web",
  ACCESS_TOKEN_TTL_MINUTES: 60,
  REFRESH_TOKEN_TTL_DAYS: 30,
  SESSION_COOKIE_NAME: "awm_session",
  REFRESH_COOKIE_NAME: "awm_refresh",
  CSRF_COOKIE_NAME: "awm_csrf",
  MFA_COOKIE_NAME: "awm_mfa",
  KEY_ROTATION_DAYS: 30,
  PASSWORD_SALT_ROUNDS: 12,
  BACKUP_CODE_COUNT: 10,
  BACKUP_CODE_LENGTH: 10,
  PASSWORD_MIN_LENGTH: 8,
  LOGIN_LOCKOUT_MINUTES: 15,
  MAX_LOGIN_ATTEMPTS: 5,
  TRUSTED_DEVICE_DAYS: 30,
} as const;

export type SecurityConstantKey = keyof typeof SECURITY_CONSTANTS;